// See https://aka.ms/new-console-template for more information

try
{

    bool itsTrue = true;

    Console.WriteLine("Hello, World!");
    Console.WriteLine("H");
    Console.WriteLine("He");
    Console.WriteLine("Hel");
    Console.WriteLine("Hell");
    Console.WriteLine("Hello");
    Console.WriteLine("Hello,");
    Console.WriteLine("Hello, ");
    Console.WriteLine("Hello, W");
    Console.WriteLine("Hello, Wo");
    Console.WriteLine("Hello, Wor");
    Console.WriteLine("Hello, Worl");
    Console.WriteLine("Hello, World");
    if (itsTrue)
    {
        global::System.Console.WriteLine("comand prompt for all app");

        iterarcadaLetra("algo es lo que estamos haciendo aca");

    }

    void iterarcadaLetra(string palabra)
    {

        if (true)
        {

            global::System.Console.WriteLine(palabra);


        }


    }




    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");
    Console.WriteLine("Hello, World");



    int NUM1, NUM2;

    double RESUL;
    string linea;

    void Any()
    {
        Console.Write("NÚMERO 1 :"); linea = Console.ReadLine();
        NUM1 = int.Parse(linea);
        Console.Write("NÚMERO 2 :"); linea = Console.ReadLine();
        NUM2 = int.Parse(linea);
        RESUL = (NUM1 + NUM2) * (NUM1 - NUM2);
        Console.WriteLine();
        Console.WriteLine("El resultado es : " + RESUL);
        Console.ReadLine();

    }

    void ani()
    {

        Console.Write("NÚMERO 1 :"); linea = Console.ReadLine();
        NUM1 = int.Parse(linea);
        Console.Write("NÚMERO 2 :"); linea = Console.ReadLine();
        NUM2 = int.Parse(linea);
        if ((NUM1 > NUM2))
        {
            Console.WriteLine("{0} ES MAYOR QUE {1}", NUM1, NUM2);
        }
        else
        {
            if ((NUM1 == NUM2))
            {
                Console.WriteLine("{0} ES IGUAL A {1}", NUM1, NUM2);
            }
            else
            {
                Console.WriteLine("{0} ES MENOR QUE {1}", NUM1, NUM2);
            }
        }
        Console.WriteLine();
        Console.WriteLine("OTRA MANERA");
        string RESUL;
        if (NUM1 > NUM2)
        {
            RESUL = "MAYOR";
        }
        else
        if (NUM1 == NUM2)
        {
            RESUL = "IGUAL";
        }
        else
        {
            RESUL = "MENOR";
        }

        Console.WriteLine("{0} ES {1} QUE {2}", NUM1, RESUL, NUM2);
        Console.Write("Pulse una Tecla:"); Console.ReadLine();

    }







    Console.WriteLine(".");
    Console.WriteLine(".");
    Console.WriteLine(".");
    Console.WriteLine(".");
    Console.WriteLine("..");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-");
    Console.WriteLine("...-6");
    Console.WriteLine("...-6");
    Console.WriteLine("...-65");
    Console.WriteLine("...-65");
    Console.WriteLine("...-65");
    Console.WriteLine("...-651");
    Console.WriteLine("...-6512");
    Console.WriteLine("...-65124");
    Console.WriteLine("...-651245");
    Console.WriteLine("...-65124545");
    Console.WriteLine("...-65124545");
    Console.WriteLine("...-6512454543");
    Console.WriteLine("...-65124545433");
    Console.WriteLine("...-651245454331");
    Console.WriteLine("...-65124545433130");
    Console.WriteLine("...-651245454331301");
    Console.WriteLine("...-65124545433130131");
    Console.WriteLine("...-65124545433130131");
    Console.WriteLine("...-65124545433130131.0");
    Console.WriteLine("...-65124545433130131.021");
    Console.WriteLine("...-65124545433130131.02135");
    Console.WriteLine("...-65124545433130131.0213521");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214");
    Console.WriteLine("...-65124545433130131.02135214321");
    Console.WriteLine("...-65124545433130131.02135214321");
    Console.WriteLine("...-65124545433130131.0213521432101");
    Console.WriteLine("...-65124545433130131.021352143210121");
    Console.WriteLine("...-65124545433130131.0213521432101211");
    Console.WriteLine("...-65124545433130131.021352143210121131");
    Console.WriteLine("");
    Console.WriteLine("");
    Console.WriteLine("");
    Console.WriteLine("");
    Console.WriteLine("");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("5414");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987");
    Console.WriteLine("54143+987/89");
    Console.WriteLine("54143+987/89");
    Console.WriteLine("54143+987/89");
    Console.WriteLine("54143+987/89");
    Console.WriteLine("54143+987/89");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965");
    Console.WriteLine("54143+987/8965+");
    Console.WriteLine("54143+987/8965+");
    Console.WriteLine("54143+987/8965+");
    Console.WriteLine("54143+987/8965+");
    Console.WriteLine("54143+987/8965+´{");
    Console.WriteLine("54143+987/8965+´{");
}
catch (global::System.Exception e)
{
    throw;
}

